/*
Baller v1.2.7

Written by muffinshades
Copyright muffinshades 2024 All Rights Reserved
Minified with the Google Closure Compiler
*/

(function(H,N,D){'use strict';function q(a,d,c,f,g,k){this.x=a;this.y=d;this.g=this.w=g;this.l=c;this.j=f;this.size=g;this.type=k;this.i=O[this.type];this.m=!1;this.update=function(){P[this.type](this)}}function I(a,d,c,f,g,k){this.count=this.i=c;this.K=f;this.C=a;this.D=d;this.N=k;this.id=g;this.done=!1;this.update=function(){this.i--;Q[this.id](this);0==this.i&&(this.N(this),this.done=!0,this.i=999)}}function r(a,d,c,f){this.x=a;this.y=d;this.L=c;this.H=1;this.J=!1;this.fill=f||"#fff";this.update=
function(){this.y-=.25;b.font="25px Arial";b.strokeStyle="#000";b.fillStyle=this.fill;b.globalAlpha=this.H;b.strokeText(this.L,this.x,this.y);b.fillText(this.L,this.x,this.y);b.globalAlpha=1;this.H-=.025;0>=this.H&&(this.J=!0)}}function J(a,d,c,f){a=b.createLinearGradient(a,d,a+c,d+f);d="#ff0 #0f0 #0ff #00f #80f #f0f".split(" ");for(c=0;c<d.length;c++)a.addColorStop(c/(d.length-1),d[c]);return a}function A(a,d,c,f){b.beginPath();b.moveTo(a,d);b.lineTo(c,f);b.stroke()}function R(){for(var a in l)for(var d in l)l[a][d]?
(a=parseInt(a),d=parseInt(d),b.fillStyle="rgb(180, 180, 252)"):b.fillStyle=S[(a^d)%2],b.fillRect(45*d,45*a,45,45);for(let g in l)for(let k in l)if(l[g][k]){g=parseInt(g);k=parseInt(k);a=45*k;d=45*g;b.strokeStyle="#000";b.lineCap="round";b.lineWidth=5;0<g&&!l[g-1][k]&&A(a,d,a+45,d);12>g&&!l[g+1][k]&&A(a,d+45,a+45,d+45);0<k&&!l[g][k-1]&&A(a,d,a,d+45);12>k&&!l[g][k+1]&&A(a+45,d,a+45,d+45);var c=e.x+e.l,f=e.y-e.j;c<a+45&&c+e.w>a&&f<d+45&&f+e.g>d&&(e.l=0,e.x=e.x>a?a+45:a-e.w);c=e.x;f=e.y+e.j;c<a+45&&c+
e.w>a&&f<d+45&&f+e.g>d&&(e.j=0,e.y=e.y>d?d+45+1:d-e.g-1)}}function E(a,d){for(;0<a.length;){for(let c in a)a[c]>a[0]&&a[c]--;d.splice(a[0],1);a.splice(0,1)}return d}function B(){return Math.floor(540*Math.random())+45}function C(){return Math.floor(540*Math.random())+45}const m=N.getElementById("c"),b=m.getContext("2d");let w=1,K=60,F=0;var l=[],x=H.getItem("hScore")||0;let h=[],t=[],n=[];var y=!1;const u=[0,250,100];let O=[null,1E3/(1E3/60)*5,1E3/(1E3/60)*3,1E3/(1E3/60)*2,1E3/(1E3/60)*4],z=[0,100,
250,500,0,1500],G=new function(a,d){this.rate=a;this.o=d;this.I=0;this.R=function(){this.I++;this.I>=this.rate&&(this.I=0,this.o())}}(60,function(){let a=.5<Math.random()?0:1,d=.5<Math.random()?0:1;h.push(new q(a*m.width,d*m.height,Math.random()*(a?-5:5),Math.random()*(d?-5:5),10,0))});var e={x:100,y:100,w:27,g:27,S:3,l:0,j:0,B:!1,u:!1,A:!1,v:!1,speed:5,G:4,h:0,s:0,end:!1,M:function(){0<this.s&&(b.globalAlpha=this.s/150,b.fillStyle="rgb(0,200,255)",b.strokeStyle="rgb(0,128,200)",b.beginPath(),b.arc(this.x+
this.w/2,this.y+this.g/2,this.w/2+20,0,2*Math.PI),b.fill(),b.stroke(),b.globalAlpha=1);b.fillStyle="rgb(255,0,0)";b.fillRect(this.x,this.y,this.w,this.g);b.strokeStyle="#000";b.lineCap="round";b.lineWidth=3.5;b.strokeRect(this.x,this.y,this.w,this.g);this.B&&this.j>-this.speed&&(this.j-=this.speed);this.u&&this.j<this.speed&&(this.j+=this.speed);this.A&&this.l<this.speed&&(this.l+=this.speed);this.v&&this.l>-this.speed&&(this.l-=this.speed);this.v||this.A||(this.l=0);this.B||this.u||(this.j=0);this.x+=
this.l*w;this.y+=this.j*w;0<this.s&&this.s--;0>=this.G&&(this.h>x&&(H.setItem("hScore",this.h),x=this.h),alert("Game Over! Score: "+this.h+" Hi: "+x),this.end=!0,D.location.reload());this.h++},O:function(a,d,c){this.G--;if(a<this.x||a>this.x+this.w)c.l*=-1;if(d<this.y||d>this.y+this.g)c.j*=-1;this.s=100;return c}};const Q=[function(a){b.globalAlpha=a.i%(a.count/a.K)/a.count;b.fillStyle="#f00";b.fillRect(45*a.C,45*a.D,45,45);b.globalAlpha=1},function(a){b.globalAlpha=a.i%(a.count/a.K)/(.5*a.count);
b.fillStyle="#f00";b.strokeStyle="#000";b.font="35px Arial";b.strokeText("!",a.C,a.D);b.fillText("!",a.C,a.D);b.globalAlpha=1}];let P=[function(a){b.fillStyle="#00f";b.fillRect(a.x,a.y,a.w,a.g);b.strokeStyle="#000";b.lineCap="round";b.lineWidth=5;b.beginPath();b.arc(a.x,a.y,a.size,0,2*Math.PI);b.fill();b.beginPath();b.arc(a.x,a.y,a.size,0,2*Math.PI);b.stroke();a.x+=a.l*w;a.y+=a.j*w;return a},function(a){a.i--;b.fillStyle="#ff0";b.fillRect(a.x,a.y,a.w,a.g);b.strokeStyle="#000";b.lineCap="round";b.lineWidth=
5;b.beginPath();b.arc(a.x,a.y,a.size,0,2*Math.PI);b.fill();b.beginPath();b.arc(a.x,a.y,a.size,0,2*Math.PI);b.stroke();b.fillStyle="#fff";b.strokeStyle="#000";b.font="25px Arial";b.strokeText(Math.floor(a.i/(1E3/(1E3/60))*10)/10,a.x-a.size/2,a.y+a.size/2);b.fillText(Math.floor(a.i/(1E3/(1E3/60))*10)/10,a.x-a.size/2,a.y+a.size/2);if(0>=a.i){a.m=!0;let d=2*Math.PI;for(let c=0;c<d;c+=d/10)h.push(new q(a.x+5*Math.cos(c),a.y+5*Math.sin(c),5*Math.cos(c),5*Math.sin(c),10,0))}return a},function(a){a.i--;b.fillStyle=
"#0ff";b.strokeStyle="#000";b.save();b.translate(a.x+a.w/2,a.y+a.g/2);b.rotate(Math.PI/4);b.fillRect(-a.w/2,-a.g/2,a.w,a.g);b.strokeRect(-a.w/2,-a.g/2,a.w,a.g);b.restore();b.fillStyle="#fff";b.strokeStyle="#000";b.font="25px Arial";b.strokeText(Math.floor(a.i/(1E3/(1E3/60))*10)/10,a.x,a.y+a.g/1.5);b.fillText(Math.floor(a.i/(1E3/(1E3/60))*10)/10,a.x,a.y+a.g/1.5);if(0>=a.i){a.m=!0;let d=2*Math.PI;for(let c=0;c<d;c+=d/4)h.push(new q(a.x+5*Math.cos(c),a.y+5*Math.sin(c),5*Math.cos(c),5*Math.sin(c),10,
0))}return a},function(a){a.P||(a.P=a.i);a.i--;b.fillStyle=J(-a.w/2+5,-a.g/2+5,a.w-10,a.g-10);b.strokeStyle="#000";b.save();b.translate(a.x+a.w/2,a.y+a.g/2);b.fillRect(-a.w/2,-a.g/2,a.w,a.g);b.strokeRect(-a.w/2,-a.g/2,a.w,a.g);b.restore();a.F||(a.F=Math.floor(450*Math.random())+50);b.fillStyle="#fff";b.strokeStyle="#000";b.font="15px Arial";b.strokeText("+"+a.F,a.x,a.y+a.g/1.5);b.fillText("+"+a.F,a.x,a.y+a.g/1.5);b.globalAlpha=1;0>=a.i&&(a.m=!0);return a},function(a){a.i--;b.fillStyle="#fff";b.strokeStyle=
"#000";b.fillRect(a.x,a.y,a.w,a.g);b.fillStyle="#f00";b.fillRect(a.x+a.w/3,a.y,a.w/3,a.g);b.fillRect(a.x,a.y+a.g/3,a.w,a.g/3);b.strokeRect(a.x,a.y,a.w,a.g);b.fillStyle="#fff";b.strokeStyle="#000";b.font="20px Arial";b.strokeText(":D",a.x,a.y+a.g/1.5);b.fillText(":D",a.x,a.y+a.g/1.5);b.globalAlpha=1;0>=a.i&&(a.m=!0);return a}];var T=[function(a,d,c){return 0>=e.s?e.O(a,d,c):c},function(a,d,c){c.m=!0;.9>Math.random()?(n.push(new r(c.x-c.size/2,c.y-20,"+"+u[c.type])),e.h+=u[c.type]):(a="+"+2*u[c.type],
n.push(new r(c.x-c.size/2,c.y-20,a,J(c.x-c.size,0,b.measureText(a).width,0))),e.h+=2*u[c.type]);return c},function(a,d,c){c.m=!0;n.push(new r(c.x-c.size/2,c.y-20,"+"+u[c.type],"#0ff"));e.h+=u[c.type];return c},function(a,d,c){c.m=!0;e.h+=c.F;n.push(new r(c.x-c.size/2,c.y-20,"+"+c.F,"#fb0"));return c},function(a,d,c){c.m=!0;e.G++;n.push(new r(c.x-c.size/2,c.y-50,"+1hp","#0f0"));n.push(new r(c.x-c.size/2,c.y-20,"-300","#f00"));e.h-=300;return c}];l=function(a,d,c){a=12+2*c;d+=2*c;c=[];for(let f=0;f<
d;f++){c[f]=[];for(let g=0;g<a;g++)c[f][g]=0==g||g>=a-1||0==f||f>=d-1?1:0}return c}(12,12,1);let S=["rgb(231, 231, 255)","rgb(245, 248, 255)"],p;var L=0;setInterval(function(){if(y)b.fillStyle="#999",b.font="30px Arial",b.fillText("Press Esc. to return to game...",100,100);else if(!e.end){F++;w=60/K;m.width=630;m.height=630;R();p=[];for(var a in t)t[a].update(),t[a].done&&p.push(a);E(p,t);p=[];for(a=0;a<h.length;a++){h[a].update();if(0>h[a].x||h[a].x>m.width||0>h[a].y||h[a].y>m.height||h[a].m){p.push(a);
e.h+=5;continue}let c=h[a].x,f=h[a].y;Math.sqrt((e.x+e.w/2-c)**2+(e.y+e.g/2-f)**2)<h[a].size+e.w/2&&(h[a]=T[h[a].type](c,f,h[a]))}E(p,h);p=[];for(var d in n)n[d].update(),n[d].J&&p.push(d);E(p,n);e.M();b.fillStyle="#fff";b.strokeStyle="#000";b.font="20px Arial";d=Math.floor(100*L)/100;b.strokeText("Health: "+e.G+" Score: "+e.h+" Time: "+d+"f High Score: "+x,5,15);b.fillText("Health: "+e.G+" Score: "+e.h+" Time: "+d+"f High Score: "+x,5,15);G.R();G.rate-=.001;for(let c in z)null!=z[c]&&(z[c]--,0>=
z[c]&&(setInterval(function(){y||M[c].o()},M[c].rate),z[c]=null));L++}},1E3/60);D.addEventListener("keydown",function(a){console.log(a);switch(a.key){case "w":e.B=!0;break;case "a":e.v=!0;break;case "s":e.u=!0;break;case "d":e.A=!0;break;case "ArrowUp":e.B=!0;break;case "ArrowLeft":e.v=!0;break;case "ArrowDown":e.u=!0;break;case "ArrowRight":e.A=!0;break;case "Escape":y=!y}});D.addEventListener("keyup",function(a){switch(a.key){case "w":e.B=!1;break;case "a":e.v=!1;break;case "s":e.u=!1;break;case "d":e.A=
!1;break;case "ArrowUp":e.B=!1;break;case "ArrowLeft":e.v=!1;break;case "ArrowDown":e.u=!1;break;case "ArrowRight":e.A=!1}});setInterval(function(){y||(K=F,F=0)},1E3);var v=[90,80];let M=[{o:function(){70<100*Math.random()&&t.push(new I(Math.floor(12*Math.random())+1,Math.floor(12*Math.random())+1,120,3,0,function(a){l[a.D][a.C]=!l[a.D][a.C]}))},rate:2E3},{o:function(){100*Math.random()>v[0]&&h.push(new q(B(),C(),0,0,15,1));v[0]-=.1},rate:750},{o:function(){100*Math.random()>v[1]&&h.push(new q(B(),
C(),0,0,25,2));v[1]-=.1},rate:500},{o:function(){let a=5+5*Math.random();for(let d=5;d<a;d++){let c=(.5<Math.random()?0:1)*m.width;c+=c>m.width/2?-35:35;t.push(new I(c,Math.random()*m.height,100,3,1,function(f){let g=f.C>m.width/2?0:1;h.push(new q(g?1:m.width-1,f.D,7*(2*g-1),0,10,0))}))}},rate:5E3},{o:function(){.7<100*Math.random()&&h.push(new q(B(),C(),0,0,35,3))},rate:9601},{o:function(){h.push(new q(B(),C(),0,0,30,4))},rate:15E3}]})(localStorage,document,window);